articulos/urls.py
from django.urls import path
from .views import *

app_name = "articulos"

urlpatterns = [
    path('', ArticlesList.as_view(), name='list_articles'),
    path('filter/', ArticlesListFilter, name='list_filter_articles'),
    path('verArticulo/<slug:slug>/', ArticlesVer.as_view(), name='ver_articles'),
    path('nuevoArticulo/', ArticlesCreate.as_view(), name='crear_articles'),
    path('EditArticulo/<int:pk>/', ArticlesUpdate.as_view(), name='edit_articles'),
    path('borrarArticulo/<int:pk>/', ArticlesDelete.as_view(), name='borrar_articles'),

]

articulos/templates/articulos/articles_confirm_delete.html
{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'articulos:list_articles' %}">Cancelar</a>
</form>
{% endblock %}

articulos/templates/articulos/crear_articulo.html
{% extends 'base.html' %}

{% block title %} Blog nuevo {% endblock %}
{% block content %}
<div class="containe">
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-2">
                Soy Juan, apacionado por la tecnologia, de tal forma que trabajaria gratis si no fuese que sin dinero no hay comida :b
                <br><br>
                {% include "loginOption.html" %}
            </div>
        <div class="col-sm-8">
          <form method="post">
              {% csrf_token %}
              {{ form.as_p }}

              <button type="submit">Guardar</button>
          </form>

      {{ form.media }}
        </div>
        <div class="col-sm-2">

        </div>
      </div>
    </div>
</div>
{% endblock content %}

articulos/templates/articulos/home_list.html
{% extends 'base.html' %}
{% block title %}
Blog Tecnologico
{% endblock %}

{% block content %}
<div class="containe">
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-2">
                Soy Juan, apacionado por la tecnologia, de tal forma que trabajaria gratis si no fuese que sin dinero no hay comida :b
                <br><br>
                {% include "loginOption.html" %}
            </div>
        <div class="col-sm-8">
         {% if object_list %}

          {% for articles in object_list %}
            <article class="secciones">
                <div>
                    <a href="{% url  'articulos:ver_articles' articles.slug %}">
                        <div class="titulosNotas">
                            {{ articles.titulo }}
                        </div>
                    </a>
                <div class="datosAutor">
                    {% for usuario in articles.autor.all %}
                        Autor: {{ usuario.username }},
                    {% endfor %}
                    {{ articles.create|date:"Y-m-d" }}
                </div>
                <div>
                    {{ articles.formatted_markdown|safe|truncatechars:150 }}
                </div>
                <a href="{% url  'articulos:ver_articles' articles.slug %}">Ver</a>
                </div>
            </article>
          {% endfor %}
         {% endif %}

         {% include "paginator.html" with page=page_obj objectFilter=objectFilter %}

        </div>
        <div class="col-sm-2">
            {% include "search.html" %}
        </div>
        </div>
      </div>
</div>
{% endblock content %}

articulos/templates/articulos/update_articulo.html
{% extends 'base.html' %}

{% block title %} Blog  Update {% endblock %}
{% block content %}
<div class="containe">
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-2">
                Soy Juan, apacionado por la tecnologia, de tal forma que trabajaria gratis si no fuese que sin dinero no hay comida :b
                <br><br>
                {% include "loginOption.html" %}
            </div>
        <div class="col-sm-8">
          <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit">Guardar</button>
          </form>

      {{ form.media }}
        </div>
        <div class="col-sm-2">

        </div>
      </div>
    </div>
</div>
{% endblock content %}

articulos/templates/articulos/ver_articulo.html
{% extends 'base.html' %}

{% block title %} Blog Ver Articulo {% endblock %}
{% block content %}
<div class="containe">
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-2">
                Soy Juan, apacionado por la tecnologia, de tal forma que trabajaria gratis si no fuese que sin dinero no hay comida :b
                <br><br>
                {% include "loginOption.html" %}
            </div>
        <div class="col-sm-8">
          {% if object %}
            <article class="secciones">
              <div>
                  <div class="titulosNotas">
                      {{ object.titulo }}
                  </div>
                  <div class="datosAutor">
                    {% for usuario in object.autor.all %}
                      Autor: {{ usuario.username }}
                    {% endfor %}
                      {{ object.create|date:"Y-m-d" }}
                  </div>
                  <div>
                      {{ object.formatted_markdown|safe }}
                  </div>
                  <div>
                      {{ object.comentario }}
                  </div>
              </div>
            </article>
          {% endif %}
        </div>
        <div class="col-sm-2">

        </div>
      </div>
    </div>
</div>
{% endblock content %}