Blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articulos.urls', namespace='articulos')),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('markdownx/', include('markdownx.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articulos/urls.py
from django.urls import path
from .views import *

app_name = "articulos"

urlpatterns = [
    path('', ArticlesList.as_view(), name='list_articles'),
    path('filter/', ArticlesListFilter, name='list_filter_articles'),
    path('verArticulo/<slug:slug>/', ArticlesVer.as_view(), name='ver_articles'),
    path('nuevoArticulo/', ArticlesCreate.as_view(), name='crear_articles'),
    path('EditArticulo/<int:pk>/', ArticlesUpdate.as_view(), name='edit_articles'),
    path('borrarArticulo/<int:pk>/', ArticlesDelete.as_view(), name='borrar_articles'),

]

urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articulos.urls', namespace='articulos')),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('markdownx/', include('markdownx.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">

  <head>
    <title>
      {% block title %}Blog{% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="description" content="Blog">
    <meta name="author" content="Aparicio Juan Jose">
    <link rel="shortcut icon" href="img/icon.png" sizes="32x32">
    <script src="//code.jquery.com/jquery-2.1.1.min.js"></script> <!-- markdown necessary -->
    <!-- Bootstrap core CSS -->
    <link href="https://bootswatch.com/4/minty/bootstrap.min.css" rel="stylesheet">
    <!-- <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet"> -->
    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/css/bootstrap.css">
    <link href=" {% static "css/style.css" %}" rel="stylesheet">
    {% block css %}{% endblock css %}
  </head>

  <body>
    <header>
      <div class="containe cabecera">
        <div class="row bg-primary ">
          <div class="col-sm-12 imagenEncabezado">

            <div class="col-sm-2">
              <img class="img-responsive MiFoto" src="{% static "img/juan.jpg" %}" alt="Yo"><br>
            </div>
            <div class="col-sm-8">
              <a class="tituloPagina"  href="/">Panacea Tecnologica</a>
            </div>
            <div class="col-sm-2">
                {# ver que poner o sacar #}
            </div>
           <!-- <div class="col-sm-5">
               <ul class="navbar-nav">
                  <li class="nav-item">
                    <h3> Fecha {% now "SHORT_DATETIME_FORMAT"  %}</h3>
                  </li>
               </ul>
            </div> -->
          </div>
        </div>
      </div>
    </header>
    <section>
    {% block content %}{% endblock content %}
    </section>
    <!-- Footer -->
    <footer class="py-2 bg-primary ">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Juan {% now "Y" %}</p>
      </div>
      <!-- /.container -->
    </footer>
  {% block js%}{% endblock %}
    <!-- Bootstrap core JavaScript
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
-->
  </body>

</html>

templates/borra-index.html
{% extends 'base.html' %}

{% block title %}
Blog
{% endblock %}

{% block navbar%}
{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	 <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Nombre de usuario:</label>
        		<input class="form-control" type="text" name="username">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Contraseña:</label>
        		<input class="form-control" type="password" name="password">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
                <a href="{% url 'password_reset' %}">Olvidé mi contraseña</a>
        		<input class="btn btn-primary" type="submit" value="Ingresar">
    	   </div>
        </div>
    </div>
</form>


{% endblock %}

templates/loginOption.html
<!--- <ul class="navbar-nav alinearDerecha"> --->
 <ul>
      {% if request.user.is_authenticated%}
          <li class="nav-item">
              {{request.user.username}}
              <a class="nav-link" href="{% url "accounts:logout" %}">logout</a>
              <a class="nav-link" href="{% url "articulos:crear_articles" %}">New Post</a>
          </li>
      {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:login" %}">Login</a>
          </li>
      {% endif %}
  </ul>

templates/paginator.html
<ul class="pager">
  <li>
    {% if page.has_previous %}
         <a href="?page={{ page.previous_page_number }}&filtro={{ objectFilter }}">Previous</a>
    {% endif %}
  </li>
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
  <li>
    {% if page.has_next %}
       <a href="?page={{ page.next_page_number }}&filtro={{ objectFilter }}">Next</a>
      {% endif %}
  </li>
</ul>

templates/search.html
  <form method="post" action="{% url "articulos:list_filter_articles" %}">
     {% csrf_token %}
     <input type="search" id="miBusqueda" name="q" placeholder="Que buscas..."><br>
     <br>
     <button type="submit">Search</button>
     <br><br>
      {{ form }}
      <button type="submit">Search</button>
  </form>